name: CI

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # --------------------------------------------------------------------------
  # Check

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src
      - uses: Swatinem/rust-cache@v2

      - name: check
        run: cargo check --target=riscv32imc-unknown-none-elf -Zbuild-std=core
      - name: check examples
        run: cargo check --target=riscv32imc-unknown-none-elf -Zbuild-std=core --examples

  # --------------------------------------------------------------------------
  # Lint

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: clippy
        run: cargo clippy -- -D warnings -A clippy::missing_safety_doc

  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: rustfmt
        run: cargo fmt -- --check
